import styles from "../../styles/Layout.module.css";
import React from "react";
import Navbar from "../Navbar";
import Head from "next/head";
import { Grid } from "@mui/material";

type LayoutProps = {
  toggleTheme?: React.MouseEventHandler<HTMLButtonElement>;
  children: React.ReactNode;
};
export default function Layout({ children, toggleTheme }: LayoutProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>mvlz - Interview Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid sx={{ bgcolor: "background.default" }}>
        <div className={styles.main}>
          <Navbar toggleTheme={toggleTheme} />
          <main>{children}</main>
        </div>
      </Grid>
    </div>
  );
}
