import { Button, Paper, TextField } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import AddIcon from "@mui/icons-material/Add";
import { useState } from "react";
import SocialForm from "../components/SocialForm";

const Home: NextPage = () => {
  const [isOpen, setIsOpen] = useState<boolean>(false);
  const [socials, setSocials] = useState<object[]>([]);
  const [social, setSocial] = useState<object>({})
  const submitHandler = () => {
    setSocials([...socials, { ...social, id: Date.now() }])

  };
  return (
    <div className={styles.container}>
      <Head>
        <title>mvlz - Interview Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Socials</p>
        <div>
          <>
            <Button variant="text" onClick={() => setIsOpen(true)}>
              <AddIcon /> Add Social
            </Button>
            {isOpen ? <SocialForm setIsOpen={setIsOpen} setSocial={setSocial} social={social} submitHandler={submitHandler} /> : ""}
            {socials && socials.map((s) => {
              return <li key={s.id}>{s.type} - {s.link}</li>

            })}
          </>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
